"""Supported overhead spans and field-edge irrigation troughs for the scene."""

import math

import bpy
from mathutils import Matrix, Vector

from .assets import MeshBuilder, material
from .lived_in import cable
from .rural_layout import (
    _edges, _polygon_inside, _polygons_intersect, _oriented_rectangle,
    _polyline_polygon_distance, _footprint_clear_of_road, distance,
)

ANCHORS = ((-.38, 8.66), (0, 8.66), (.38, 8.66), (-.27, 6.18))


def _rotating_instances(name, placements, source, collection, modifier_name):
    """Instance one reusable asset from points carrying a Z rotation."""

    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata([(x, y, z) for x, y, z, _ in placements], [], [])
    mesh.update()
    rotations = mesh.attributes.new('rural_rotation', 'FLOAT_VECTOR', 'POINT')
    for item, (_, _, _, angle) in zip(rotations.data, placements):
        item.vector = (0., 0., angle)
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    group = bpy.data.node_groups.new(name + ' / GN', 'GeometryNodeTree')
    group.interface.new_socket(name='Geometry', in_out='INPUT', socket_type='NodeSocketGeometry')
    group.interface.new_socket(name='Geometry', in_out='OUTPUT', socket_type='NodeSocketGeometry')
    nodes, links = group.nodes, group.links
    source_input = nodes.new('NodeGroupInput')
    info = nodes.new('GeometryNodeObjectInfo')
    info.inputs['Object'].default_value = source
    info.inputs['As Instance'].default_value = True
    rotation = nodes.new('GeometryNodeInputNamedAttribute')
    rotation.data_type = 'FLOAT_VECTOR'
    rotation.inputs['Name'].default_value = 'rural_rotation'
    instance = nodes.new('GeometryNodeInstanceOnPoints')
    output = nodes.new('NodeGroupOutput')
    links.new(source_input.outputs['Geometry'], instance.inputs['Points'])
    links.new(info.outputs['Geometry'], instance.inputs['Instance'])
    links.new(rotation.outputs['Attribute'], instance.inputs['Rotation'])
    links.new(instance.outputs['Instances'], output.inputs['Geometry'])
    obj.modifiers.new(modifier_name, 'NODES').node_group = group
    return obj


def _wire_curve_input(name, paths, wire_material, collection):
    """Create a multi-spline wire input whose tube is generated by GN."""

    data = bpy.data.curves.new(name, 'CURVE')
    data.dimensions = '3D'
    data.resolution_u = 1
    for path in paths:
        spline = data.splines.new('POLY')
        spline.points.add(len(path) - 1)
        for point, coordinate in zip(spline.points, path):
            point.co = (*coordinate, 1.)
    obj = bpy.data.objects.new(name, data)
    collection.objects.link(obj)
    group = bpy.data.node_groups.new(name + ' / GN', 'GeometryNodeTree')
    group.interface.new_socket(name='Geometry', in_out='INPUT', socket_type='NodeSocketGeometry')
    group.interface.new_socket(name='Geometry', in_out='OUTPUT', socket_type='NodeSocketGeometry')
    nodes, links = group.nodes, group.links
    source_input = nodes.new('NodeGroupInput')
    profile = nodes.new('GeometryNodeCurvePrimitiveCircle')
    profile.inputs['Resolution'].default_value = 8
    profile.inputs['Radius'].default_value = .016
    curve_to_mesh = nodes.new('GeometryNodeCurveToMesh')
    curve_to_mesh.inputs['Fill Caps'].default_value = True
    shade = nodes.new('GeometryNodeSetMaterial')
    shade.inputs['Material'].default_value = wire_material
    output = nodes.new('NodeGroupOutput')
    links.new(source_input.outputs['Geometry'], curve_to_mesh.inputs['Curve'])
    links.new(profile.outputs['Curve'], curve_to_mesh.inputs['Profile Curve'])
    links.new(curve_to_mesh.outputs['Mesh'], shade.inputs['Geometry'])
    links.new(shade.outputs['Geometry'], output.inputs['Geometry'])
    obj.modifiers.new('Rural wires / Geometry Nodes', 'NODES').node_group = group
    obj['rural_role'] = 'wires_gn'
    obj['spline_count'] = len(paths)
    return obj


def _edge_guard(zone, edge_index, start, end):
    """Return the plan-view guard for one station interval on a zone edge."""

    a, b = _edges(zone.polygon)[edge_index]
    length = distance(a, b)
    tangent = ((b[0] - a[0]) / length, (b[1] - a[1]) / length)
    mid = (start + end) / 2
    center = (a[0] + tangent[0] * mid, a[1] + tangent[1] * mid)
    return _oriented_rectangle(center, tangent, end - start, .8)


def _replace_channel_mesh(channel, zone, edge_index, start, end, farm):
    """Rebuild one open-channel object after extending one of its ends."""

    from .rural_culverts import trough

    a, b = _edges(zone.polygon)[edge_index]
    length = distance(a, b)
    tangent = ((b[0] - a[0]) / length, (b[1] - a[1]) / length)
    center = Vector((a[0] + tangent[0] * ((start + end) / 2),
                     a[1] + tangent[1] * ((start + end) / 2), 0))
    transform = Matrix.Translation(center) @ Matrix.Rotation(
        math.atan2(tangent[1], tangent[0]), 4, 'Z')
    builder = MeshBuilder()
    trough(builder, end - start, farm)
    builder.transform(transform)
    replacement = builder.object('Channel corner extension', channel.users_collection[0])
    old = channel.data
    channel.data = replacement.data
    bpy.data.objects.remove(replacement, do_unlink=True)
    if not old.users:
        bpy.data.meshes.remove(old)
    channel['station_start'] = start
    channel['station_end'] = end
    channel['length'] = end - start
    channel['footprint'] = [value for point in _edge_guard(zone, edge_index, start, end)
                            for value in point]


def connect_channel_corners(root, layout, homes, poles, farm, external_guards=()):
    """Join safe adjacent field-edge channel runs at the same polygon vertex.

    Straight channel runs intentionally stop half a metre before a field corner
    so their end caps do not collide.  When both neighbouring runs reach that
    corner and the short extensions are clear, rebuild their end stations to
    the shared vertex.  The result remains editable as two ordinary channel
    runs, which keeps the source station data useful for later intakes or flow
    work.  Corners near a road, property obstruction, or another service stay
    open.
    """

    blocked = [v.footprint for h in homes for v in h.buildings]
    blocked += [p for h in homes for p in (h.access, h.driveway) if p]
    channels = [o for o in root.all_objects if o.get('rural_role') == 'canal']
    zones = {z.id: z for z in layout.zones}
    by_edge = {}
    for channel in channels:
        by_edge.setdefault((channel['zone_id'], channel['edge_index']), []).append(channel)
    guard_map = {}
    for channel in channels:
        zone = zones[channel['zone_id']]
        guard_map[channel.name] = _edge_guard(
            zone, channel['edge_index'], channel['station_start'], channel['station_end'])
    external = tuple(external_guards)
    joined = 0

    for zone in layout.zones:
        if zone.kind != 'field':
            continue
        zone_edges = _edges(zone.polygon)
        for vertex_index in range(len(zone_edges)):
            previous_edge = (vertex_index - 1) % len(zone_edges)
            next_edge = vertex_index
            previous_length = distance(*zone_edges[previous_edge])
            next_length = distance(*zone_edges[next_edge])
            previous = max(
                by_edge.get((zone.id, previous_edge), ()),
                key=lambda obj: obj['station_end'], default=None)
            following = min(
                by_edge.get((zone.id, next_edge), ()),
                key=lambda obj: obj['station_start'], default=None)
            if previous is None or following is None or previous is following:
                continue
            previous_gap = previous_length - previous['station_end']
            following_gap = following['station_start']
            if not (.02 <= previous_gap <= .65 and .02 <= following_gap <= .65):
                continue

            previous_extension = _edge_guard(
                zone, previous_edge, previous['station_end'], previous_length)
            following_extension = _edge_guard(
                zone, next_edge, 0., following['station_start'])
            extensions = (previous_extension, following_extension)
            if any(not _polygon_inside(guard, layout.boundary) for guard in extensions):
                continue
            if any(not _footprint_clear_of_road(guard, road, .5)
                   for guard in extensions for road in layout.roads):
                continue
            if any(_polygons_intersect(guard, polygon)
                   for guard in extensions for polygon in blocked):
                continue
            if any(_polygons_intersect(guard, reserved.polygon)
                   for guard in extensions
                   for reserved in layout.zones if reserved.kind == 'reserved'):
                continue
            if any(_polygons_intersect(guard, other)
                   for guard in extensions for other in external):
                continue
            if any(_polygons_intersect(guard, other)
                   for guard in extensions
                   for name, other in guard_map.items()
                   if name not in {previous.name, following.name}):
                continue
            if any(_polyline_polygon_distance(
                    (tuple(p.location[:2]), tuple(p.location[:2])), guard) < .9
                   for guard in extensions for p in poles):
                continue

            _replace_channel_mesh(previous, zone, previous_edge,
                                  previous['station_start'], previous_length, farm)
            _replace_channel_mesh(following, zone, next_edge,
                                  0., following['station_end'], farm)
            guard_map[previous.name] = _edge_guard(
                zone, previous_edge, previous['station_start'], previous_length)
            guard_map[following.name] = _edge_guard(
                zone, next_edge, 0., following['station_end'])
            joined += 1

    root['canal_corner_connections'] = joined
    return joined


def add_services(root, layout, homes, farm, *, cable_sag=.55, max_span=40.):
    """Rebuild-time geometry; skip obstructed spans and channel sections.

    Channels are raised, open concrete troughs. Eligible road gaps are connected
    by buried box conduits; no hydraulic flow simulation is performed.
    """
    if not math.isfinite(cable_sag) or not 0 <= cable_sag <= 1.5:
        raise ValueError('cable_sag must be between 0 and 1.5 m')
    if not math.isfinite(max_span) or not 5 <= max_span <= 60:
        raise ValueError('max_span must be between 5 and 60 m')
    bpy.context.view_layer.update()
    poles = [o for o in root.all_objects if o.get('rural_role') == 'pole']
    blocked = [v.footprint for h in homes for v in h.buildings]
    blocked += [p for h in homes for p in (h.access, h.driveway) if p]
    from .street_assets import ensure_street_assets
    pole_source = ensure_street_assets()['Pole']
    pole_collection = (poles[0].users_collection[0] if poles
                       else bpy.data.collections.new('Rural utility poles'))
    if pole_collection.name not in [c.name for c in root.children]:
        root.children.link(pole_collection)
    pole_placements = [(pole.location.x, pole.location.y, pole.location.z,
                        pole.rotation_euler.z) for pole in poles]
    pole_host = _rotating_instances('Rural utility poles / GN points', pole_placements,
                                    pole_source, pole_collection, 'Rural poles / Geometry Nodes')
    pole_host['rural_role'] = 'poles_gn'
    pole_host['instance_count'] = len(pole_placements)
    for pole in poles:
        pole.hide_render = True
        pole.hide_set(True)
    root['poles_gn'] = True
    root['pole_instance_count'] = len(pole_placements)
    wires = bpy.data.collections.new('Rural overhead wires')
    root.children.link(wires)
    black = material('Rural cable insulation', (.012, .015, .014), roughness=.65)
    wire_paths = []
    span_count = 0
    for road in layout.roads:
        ordered = sorted((p for p in poles if p['road_id'] == road.id), key=lambda p: p['road_station'])
        for first, second in zip(ordered, ordered[1:]):
            length = (second.location - first.location).length
            if length > max_span:
                continue
            # A conservative strip also excludes wires over lower houses.
            a, b = tuple(first.location[:2]), tuple(second.location[:2])
            direction = ((b[0] - a[0]) / length, (b[1] - a[1]) / length)
            guard = _oriented_rectangle(((a[0] + b[0]) / 2, (a[1] + b[1]) / 2), direction, length, 1.5)
            if not _polygon_inside(guard, layout.boundary) or any(_polygons_intersect(guard, p) for p in blocked):
                continue
            for index, (across, height) in enumerate(ANCHORS):
                start = first.matrix_world @ Vector((0, across, height))
                end = second.matrix_world @ Vector((0, across, height))
                points = [start.lerp(end, i / 24) - Vector((0, 0, 4 * cable_sag * (i / 24) * (1 - i / 24)))
                          for i in range(25)]
                wire_paths.append([tuple(point) for point in points])
                builder = MeshBuilder()
                cable(builder, points, .016, black)
                obj = builder.object(f'Wire / {first.name} / {index}', wires)
                obj['rural_role'] = 'wire'
                obj['pole_start'] = first.name
                obj['pole_end'] = second.name
                obj['anchor_index'] = index
                obj['sag'] = cable_sag
                obj.hide_render = True
                obj.hide_set(True)
            span_count += 1
    _wire_curve_input('Rural overhead wires / GN paths', wire_paths, black, wires)
    root['wires_gn'] = True
    root['wire_gn_spline_count'] = len(wire_paths)
    channels = bpy.data.collections.new('Rural irrigation channels')
    root.children.link(channels)
    guards = []
    # Use original field-zone boundaries: no duplicated parallel channels along
    # both sides of every subdivision gap. Corners stop short to avoid overlap.
    for zone in layout.zones:
        if zone.kind != 'field':
            continue
        for edge_index, (a, b) in enumerate(_edges(zone.polygon)):
            length = distance(a, b)
            tangent = ((b[0] - a[0]) / length, (b[1] - a[1]) / length)
            segments = max(1, math.ceil(length / 2.))
            valid = []
            def footprint(start, end):
                mid = (start + end) / 2
                return _oriented_rectangle((a[0] + tangent[0] * mid, a[1] + tangent[1] * mid), tangent, end - start, .8)
            for index in range(segments):
                start, end = max(.5, index * length / segments), min(length - .5, (index + 1) * length / segments)
                if end <= start:
                    continue
                guard = footprint(start, end)
                if (not _polygon_inside(guard, layout.boundary)
                    or any(not _footprint_clear_of_road(guard, road, .5) for road in layout.roads)
                    or any(_polygons_intersect(guard, p) for p in blocked)
                    or any(_polyline_polygon_distance((tuple(p.location[:2]), tuple(p.location[:2])), guard) < .9 for p in poles)):
                    continue
                if valid and abs(valid[-1][1] - start) < 1e-6:
                    valid[-1] = (valid[-1][0], end)
                else:
                    valid.append((start, end))
            for run_index, (start, end) in enumerate(valid):
                guard = footprint(start, end)
                if any(_polygons_intersect(guard, other) for other in guards):
                    continue
                mid = (start + end) / 2
                center = Vector((a[0] + tangent[0] * mid, a[1] + tangent[1] * mid, 0))
                transform = Matrix.Translation(center) @ Matrix.Rotation(math.atan2(tangent[1], tangent[0]), 4, 'Z')
                builder = MeshBuilder()
                run_length = end - start
                builder.box((0, 0, .10), (run_length, .8, .12), farm['concrete'])
                for side in (-1, 1):
                    builder.box((0, side * .34, .30), (run_length, .12, .40), farm['concrete'])
                builder.add([(-run_length / 2, -.28, .28), (run_length / 2, -.28, .28),
                             (run_length / 2, .28, .28), (-run_length / 2, .28, .28)], [(0, 1, 2, 3)], farm['water'])
                builder.transform(transform)
                obj = builder.object(f'Canal / {zone.id}:{edge_index}:{run_index}', channels)
                obj['rural_role'] = 'canal'
                obj['zone_id'] = zone.id
                obj['edge_index'] = edge_index
                obj['station_start'] = start
                obj['station_end'] = end
                obj['length'] = run_length
                obj['footprint'] = [c for point in guard for c in point]
                guards.append(guard)
    from .rural_culverts import connect_road_gaps
    culvert_guards = connect_road_gaps(root, layout, homes, poles, farm)
    connect_channel_corners(root, layout, homes, poles, farm, culvert_guards)
    guards = [tuple(zip(list(obj['footprint'])[::2], list(obj['footprint'])[1::2]))
              for obj in channels.objects]
    guards.extend(culvert_guards)
    for obj in list(root.all_objects):
        if obj.get('rural_role') != 'crops':
            continue
        radius = obj['crop_radius']
        points = [tuple(v.co) for v in obj.data.vertices if all(
            _polyline_polygon_distance(((v.co.x, v.co.y), (v.co.x, v.co.y)), guard) > radius + .1 for guard in guards)]
        obj.data.clear_geometry()
        obj.data.from_pydata(points, [], [])
        obj.data.update()
        obj['crop_count'] = len(points)
    root['wire_spans'] = span_count
    root['canal_runs'] = len(channels.objects)
    root['canal_length'] = sum(o['length'] for o in channels.objects)
    root['crop_count'] = sum(o['crop_count'] for o in root.all_objects if o.get('rural_role') == 'crops')
    root['cable_sag'] = cable_sag
    root['max_wire_span'] = max_span
